# Generated by Django 6.0.7 on 2026-08-03 15:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CargaReporte',
            fields=[
                ('id_carga', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('tipo_carga', models.CharField(choices=[('CARGA_INFORME', 'Carga de Informe (Listado Básico + Ventas)'), ('DETALLE_COMPRA', 'Detallado de Compra')], default='CARGA_INFORME', max_length=20)),
            ],
            options={
                'verbose_name': 'Carga de Reporte',
                'verbose_name_plural': 'Cargas de Reportes',
                'db_table': 'cargas_reportes',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_random', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('codigo_mantis', models.CharField(max_length=100, unique=True)),
                ('barras', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('laboratorio', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='DetalleInforme',
            fields=[
                ('id_formulario', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('stock', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('rentabilidad', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('rotacion', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('duracion', models.DecimalField(decimal_places=1, default=0, max_digits=12)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('pedidos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('solicitar', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ind_duracion', models.CharField(blank=True, max_length=50, null=True)),
                ('periodo_inicio', models.DateField(blank=True, null=True)),
                ('periodo_fin', models.DateField(blank=True, null=True)),
                ('periodo_meses', models.PositiveIntegerField(blank=True, null=True)),
                ('carga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='informe.cargareporte')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='informe.producto')),
            ],
            options={
                'verbose_name': 'Detalle de Informe',
                'verbose_name_plural': 'Detalles de Informes',
                'db_table': 'detalle_informes',
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_compra', models.DateField()),
                ('factura', models.CharField(max_length=100)),
                ('proveedor', models.CharField(max_length=255)),
                ('valor_compra', models.DecimalField(decimal_places=2, max_digits=12)),
                ('periodo_inicio', models.DateField(blank=True, null=True)),
                ('periodo_fin', models.DateField(blank=True, null=True)),
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='informe.producto')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'db_table': 'compras',
                'ordering': ['-fecha_compra'],
                'constraints': [models.UniqueConstraint(fields=('producto', 'factura', 'fecha_compra'), name='unique_compra_producto_factura_fecha')],
            },
        ),
        migrations.CreateModel(
            name='Categorizacion',
            fields=[
                ('id_categorizacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('tipo_categoria', models.CharField(choices=[('A', 'Categoría A'), ('B', 'Categoría B'), ('C', 'Categoría C')], max_length=1)),
                ('analisis', models.TextField(blank=True, null=True)),
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, related_name='categorizaciones', to='informe.producto')),
            ],
            options={
                'verbose_name': 'Categorización',
                'verbose_name_plural': 'Categorizaciones',
                'db_table': 'categorizaciones',
                'ordering': ['-fecha_registro'],
                'constraints': [models.UniqueConstraint(fields=('producto',), name='unique_categorizacion_producto')],
            },
        ),
        migrations.CreateModel(
            name='ProductoExcluido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, related_name='exclusiones', to='informe.producto')),
            ],
            options={
                'verbose_name': 'Producto Excluido',
                'verbose_name_plural': 'Productos Excluidos',
                'db_table': 'productos_excluidos',
                'ordering': ['-fecha_creacion'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('producto',), name='unique_producto_activo')],
            },
        ),
        migrations.CreateModel(
            name='Vencimiento',
            fields=[
                ('id_vencimiento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField()),
                ('lote', models.CharField(max_length=100)),
                ('unidades', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, related_name='vencimientos', to='informe.producto')),
            ],
            options={
                'verbose_name': 'Vencimiento',
                'verbose_name_plural': 'Vencimientos',
                'db_table': 'fechas_vencimiento',
                'ordering': ['fecha_vencimiento'],
                'constraints': [models.UniqueConstraint(fields=('producto', 'lote'), name='unique_producto_lote')],
            },
        ),
    ]
