# Generated by Django 6.0.7 on 2026-07-15 17:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CargaReporte',
            fields=[
                ('id_carga', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('archivo_listado_basico', models.FileField(upload_to='cargas/listado_basico/')),
                ('archivo_ventas', models.FileField(upload_to='cargas/ventas/')),
                ('tipo_carga', models.CharField(choices=[('INVENTARIO', 'Inventario'), ('VENTAS', 'Ventas'), ('AMBOS', 'Ambos')], default='AMBOS', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_random', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('codigo_mantis', models.CharField(max_length=100, unique=True)),
                ('barras', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('laboratorio', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleInforme',
            fields=[
                ('id_formulario', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('stock', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('rentabilidad', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('rotacion', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('duracion', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('pedidos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ind_duracion', models.CharField(blank=True, max_length=50, null=True)),
                ('carga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='informe.cargareporte')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='informe.producto')),
            ],
        ),
    ]
