# Generated by Django 6.0.7 on 2026-07-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleinforme',
            name='rentabilidad',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
    ]
