# Generated by Django 6.0.7 on 2026-07-15 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informe', '0003_alter_detalleinforme_rentabilidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoExcluido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, related_name='exclusiones', to='informe.producto')),
            ],
            options={
                'verbose_name': 'Producto Excluido',
                'verbose_name_plural': 'Productos Excluidos',
                'ordering': ['-fecha_creacion'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('producto',), name='unique_producto_activo')],
            },
        ),
    ]
