# Generated by Django 6.0.7 on 2026-07-15 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informe', '0004_productoexcluido'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleinforme',
            name='solicitar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='detalleinforme',
            name='duracion',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='detalleinforme',
            name='rotacion',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
    ]
