# Generated by Django 6.0.7 on 2026-07-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informe', '0005_detalleinforme_solicitar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleinforme',
            name='periodo_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleinforme',
            name='periodo_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
