# Generated by Django 6.0.7 on 2026-07-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informe', '0006_detalleinforme_periodo_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleinforme',
            name='periodo_meses',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
