# Generated by Django 6.0.7 on 2026-07-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informe', '0007_detalleinforme_periodo_meses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargareporte',
            name='archivo_listado_basico',
        ),
        migrations.RemoveField(
            model_name='cargareporte',
            name='archivo_ventas',
        ),
        migrations.AlterField(
            model_name='cargareporte',
            name='tipo_carga',
            field=models.CharField(choices=[('CARGA_INFORME', 'Carga de Informe (Listado Básico + Ventas)'), ('DETALLE_COMPRA', 'Detallado de Compra')], default='CARGA_INFORME', max_length=20),
        ),
    ]
