# Generated by Django 6.0.7 on 2026-07-16 20:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informe', '0008_remove_cargareporte_archivo_listado_basico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_compra', models.DateField()),
                ('factura', models.CharField(max_length=100)),
                ('proveedor', models.CharField(max_length=255)),
                ('valor_compra', models.DecimalField(decimal_places=2, max_digits=12)),
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='informe.producto')),
            ],
            options={
                'verbose_name': 'compra',
                'verbose_name_plural': 'compras',
                'ordering': ['-fecha_compra'],
            },
        ),
    ]
