# Generated by Django 6.0.7 on 2026-07-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informe', '0009_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='periodo_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='periodo_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
