# Generated by Django 6.0.7 on 2026-07-16 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informe', '0010_compra_periodo_fin_compra_periodo_inicio'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='compra',
            constraint=models.UniqueConstraint(fields=('producto', 'factura', 'fecha_compra'), name='unique_compra_producto_factura_fecha'),
        ),
    ]
