# Generated by Django 6.0.7 on 2026-07-21 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informe', '0011_compra_unique_compra_producto_factura_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorizacion',
            fields=[
                ('id_categorizacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('tipo_categoria', models.CharField(choices=[('A', 'Categoría A'), ('B', 'Categoría B'), ('C', 'Categoría C')], max_length=1)),
                ('analisis', models.TextField(blank=True, null=True)),
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, related_name='categorizaciones', to='informe.producto')),
            ],
            options={
                'verbose_name': 'Categorización',
                'verbose_name_plural': 'Categorizaciones',
                'ordering': ['-fecha_registro'],
                'constraints': [models.UniqueConstraint(fields=('producto',), name='unique_categorizacion_producto')],
            },
        ),
    ]
