# Generated by Django 6.0.7 on 2026-07-28 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informe', '0012_categorizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vencimiento',
            fields=[
                ('id_vencimiento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField()),
                ('lote', models.CharField(max_length=100)),
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, related_name='vencimientos', to='informe.producto')),
            ],
            options={
                'verbose_name': 'Vencimiento',
                'verbose_name_plural': 'Vencimientos',
                'ordering': ['fecha_vencimiento'],
                'constraints': [models.UniqueConstraint(fields=('producto', 'lote'), name='unique_producto_lote')],
            },
        ),
    ]
