# Generated by Django 6.0.7 on 2026-07-29 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informe', '0013_vencimiento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargareporte',
            options={'verbose_name': 'Carga de Reporte', 'verbose_name_plural': 'Cargas de Reportes'},
        ),
        migrations.AlterModelOptions(
            name='compra',
            options={'ordering': ['-fecha_compra'], 'verbose_name': 'Compra', 'verbose_name_plural': 'Compras'},
        ),
        migrations.AlterModelOptions(
            name='detalleinforme',
            options={'verbose_name': 'Detalle de Informe', 'verbose_name_plural': 'Detalles de Informes'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelTable(
            name='cargareporte',
            table='cargas_reportes',
        ),
        migrations.AlterModelTable(
            name='categorizacion',
            table='categorizaciones',
        ),
        migrations.AlterModelTable(
            name='compra',
            table='compras',
        ),
        migrations.AlterModelTable(
            name='detalleinforme',
            table='detalle_informes',
        ),
        migrations.AlterModelTable(
            name='producto',
            table='productos',
        ),
        migrations.AlterModelTable(
            name='productoexcluido',
            table='productos_excluidos',
        ),
        migrations.AlterModelTable(
            name='vencimiento',
            table='fechas_vencimiento',
        ),
    ]
