# Generated by Django 6.0.7 on 2026-07-31 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informe', '0014_alter_cargareporte_options_alter_compra_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vencimiento',
            name='unidades',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
